version: "3"
services:

  web:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    command: flask run --host=0.0.0.0
    volumes:
    - ".:/app"
    ports:
    - "5000:5000"
    depends_on:
    - "db"
    environment:
      FLASK_APP: app.py

  db:
    image: "postgres:11"
    volumes:
    - "pgdata:/var/lib/postgresql/data"

volumes:
     pgdata: